### PR TITLE
This PR just adds comments to some code and changes some code style.

### PR DESCRIPTION
**Pull request by aozeyu**
Signed-off-by:

## Pre-Checklist

Note: Please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/bytedance/bitsail/blob/master/docs/contributing.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests.

## Purpose

Some description about what this PR wants to do.

## Approaches

Some description about how this PR achives the purpose. 

## Related Issues

_e.g._ Close #796

## New Behavior (screenshots if needed)

N/A

### CODE REVIEW

**Comment by aozeyu** [comment]
@microxxx @lark @snakev

**Comment by ayonel** [comment]
> @microxxx @lark @snakev
these users are not bitsail reviewers. please    @BlockLiu or @lichang-bd

**Comment by aozeyu** [comment]
@BlockLiu @lichang-bd

**Review by BlockLiu — APPROVED** [review]

**Comment by BlockLiu** [comment]
lgtm!

**Pull request merged**
