### PR TITLE
[BitSail][Actions]workflow support thrift compile

### PR DESCRIPTION
**Pull request by DongLiang-0**
Signed-off-by:

## Pre-Checklist

Note: Please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/bytedance/bitsail/blob/master/docs/contributing.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests.

## Purpose

Some description about what this PR wants to do.

## Approaches

Some description about how this PR achives the purpose. 

## Related Issues

_e.g._ Close #796

## New Behavior (screenshots if needed)

N/A

### CODE REVIEW

**Comment by lichang-bd** [comment]
LGTM, thanks for your contribution， have a look too @garyli1019

**Review by lichang-bd — APPROVED** [review]

**Comment by DongLiang-0** [comment]
> LGTM, thanks for your contribution， have a look too @garyli1019

There is still a problem with the windows environment. I have been busy with other things these days, so I need to test again

**Comment by garyli1019** [comment]
to run unit test on Windows has many issues, I guess to could disable the UT on windows and compile only? @lichang-bd

**Comment by lichang-bd** [comment]
> to run unit test on Windows has many issues, I guess to could disable the UT on windows and compile only? @lichang-bd

yes, I think so， for windows ,we can create a new issue @lichang-bd @DongLiang-0

**Comment by garyli1019** [comment]
@lichang-bd i mean disable all UTs for windows and compile only

**Comment by lichang-bd** [comment]
> 

OK

**Comment by DongLiang-0** [comment]
I tried many times but couldn't install the thrift plugin on windows. The general reason is that powershell is used on github, and it cannot be switched to cmd, resulting in various installation problems.

Is it possible to delete the windows compilation? I see that the compilation of bitsail is based on maven. I understand that it has nothing to do with which platform it is on. @lichang-bd @garyli1019

**Comment by DongLiang-0** [comment]
Only keep macos and ubuntu for compilation and testing.

**Comment by garyli1019** [comment]
hi @DongLiang-0 , I'd like to learn more about the background of this PR. What does this thrift compiler do and why do we need it?

**Comment by DongLiang-0** [comment]
> hi @DongLiang-0 , I'd like to learn more about the background of this PR. What does this thrift compiler do and why do we need it?
In doirs source connector, dorisClient needs to be compiled by thrift.
you can refer to: https://github.com/bytedance/bitsail/pull/348

**Comment by garyli1019** [comment]
@DongLiang-0 is the Thrift compiler a must-have option for Doris or optional? We do have some users using Windows for development so I think it's necessary to include that in CICD.

**Comment by DongLiang-0** [comment]
> 
This is a necessary option, dorisClient must be compiled through thrift before it can be used.

I tried many ways to integrate the thrift plugin in windows, but all failed. Or could you guys help me figure out a way to integrate the thrift plugin into a windows environment?

**Comment by garyli1019** [comment]
Hi @DongLiang-0 , how about we add a maven flag to disable compiling doris related modules, and in the Windows CICD, we can add that flag to the maven command. Like `mvn clean verify xxx skipDoris=true`

**Comment by DongLiang-0** [comment]
> 

Thanks for the suggestion, it's a good idea

**Comment by DongLiang-0** [comment]
@garyli1019 PTAL. 
I changed the execution environment of windows to cmd, and it looks ok.

**Comment by DongLiang-0** [comment]
Apache doris will build the doris-sdk repository to solve such problems

**Pull request closed without merging**
