### PR TITLE
Updated copyright #359

### PR DESCRIPTION
**Pull request by piyush280599**
- [x] I have read through the [CONTRIBUTING.md](https://github.com/bytedance/bitsail/blob/master/docs/contributing.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).

### CODE REVIEW

**Comment by yucongcong654** [comment]
Hi piyush280599, thanks for your contribution to the BitSail community. we build a group for all contributor.Here is the QR code. If it expires, you can add WeChat ID 13651994967. Look forward to your arrival! @piyush280599 
1291676000715_ pic

**Comment by piyush280599** [comment]
@yucongcong654 Thank you for the invitation but wechat is banned in my country :(

**Comment by yucongcong654** [comment]
Is Slack available? @piyush280599

**Comment by piyush280599** [comment]
@yucongcong654 Yes Slack is available!

**Comment by yucongcong654** [comment]
You can join Bitsail's slack @piyush280599 ，Also what is your email address?

**Comment by piyush280599** [comment]
@yucongcong654 its piyush.mishra.2805@gmail.com

**Comment by yucongcong654** [comment]
I sent you an email, please check it @piyush280599

**Pull request merged**
