### PR TITLE
[BitSail][Docs] fix code highlight

### LINKED ISSUE #290: [BitSail][Docs] code highlight error in JDBC Connector example
## Describe the bug
code highlight error in JDBC Connector example

## To Reproduce

See https://bytedance.github.io/bitsail/zh/documents/connectors/jdbc/jdbc-example.html
and https://bytedance.github.io/bitsail/en/documents/connectors/jdbc/jdbc_example.html

## Expected behavior

I found that  json configuration code highlight is not shown rightly in JDBC connector example docs.

## Screenshots

image

## Build Environment

No.

## Execution Environment

No.

### PR DESCRIPTION
**Pull request by liuxiaocs7**
Signed-off-by:

## Pre-Checklist

Note: Please complete **_ALL_** items in the following checklist.

- [x] I have read through the [CONTRIBUTING.md](https://github.com/bytedance/bitsail/blob/master/docs/contributing.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests.

## Purpose

as title.

## Approaches

Some description about how this PR achives the purpose. 

## Related Issues

Close #290

## New Behavior (screenshots if needed)

N/A

### CODE REVIEW

**Review by healchow — APPROVED** [review]

**Comment by healchow** [comment]
It is recommended to create an Issue first, and then associate this PR with the Issue you made.

**Comment by liuxiaocs7** [comment]
> @liuxiaocs7 It is recommended to create an Issue first, and then associate this PR with the Issue you made.

Thank you for your kind suggestion, I will follow the steps next time.

**Comment by healchow** [comment]
> > @liuxiaocs7 It is recommended to create an Issue first, and then associate this PR with the Issue you made.
> 
> Thank you for your kind suggestion, I will follow the steps next time.

@liuxiaocs7 It is strongly recommended to add an Issue now so that each PR has its own Issue.

A good way is to make every change for a reason.

**Comment by liuxiaocs7** [comment]
> > > @liuxiaocs7 It is recommended to create an Issue first, and then associate this PR with the Issue you made.
> > 
> > 
> > Thank you for your kind suggestion, I will follow the steps next time.
> 
> @liuxiaocs7 It is strongly recommended to add an Issue now so that each PR has its own Issue.
> 
> A good way is to make every change for a reason.

OK，i'll create an issue to associate this pr right now.

**Comment by liuxiaocs7** [comment]
try to close #290 

After fix:

image

@healchow thanks for your guide, do you think it's ok?

**Comment by healchow** [comment]
@liuxiaocs7 Please modify the description of PR.
image

After modification, the Issue will be automatically associated on the right tab.

image

**Comment by liuxiaocs7** [comment]
@healchow got it, done.

**Pull request merged**
